-- AlterTable
ALTER TABLE "Asset" ADD COLUMN     "autoRotate" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "exposure" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "shadowIntensity" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "shadowSoftness" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "skyboxImage" TEXT,
ADD COLUMN     "toneMapping" TEXT NOT NULL DEFAULT 'auto';
